"""empty message

Revision ID: 20a70518244c
Revises: 
Create Date: 2024-08-29 11:33:20.853205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a70518244c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('released', sa.String(length=90), nullable=False),
    sa.Column('director', sa.String(length=90), nullable=False),
    sa.Column('genre', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
